### ISSUE TITLE
CB05 doesn't run at low NOx

### ISSUE THREAD

**Issue by marybarthbrock** [NCAR/music-box-interactive-client#238] opened 2024-03-07 17:42 UTC
**Describe the bug**
One test case that failed is when I set NO_emissions to zero on the web interface. MusicBox kept spinning.

**To Reproduce**

1. Go to Initial Conditions
2. Change NO emissions rate (near bottom) to 0
3. Run MusicBox

**Expected behavior**
MusicBox kept spinning without solving the ODEs

**Desktop (please complete the following information):**

- Browser Chrome,122.0.6261.112

**Comment by K20shores** [comment] 2024-03-27 15:18
Unable to reproduce, either on [the website](https://musicbox.acom.ucar.edu) or on my local computer. It's possible this was a server issue that was fixed in a restart since this was filed.

**Closed by K20shores** 2024-03-27 15:18 UTC
Labels: bug
